Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Diagnostics;
using WebBanHangLapTop.Areas.Admin.Models;
using WebBanHangLapTop.IRepository;
using WebBanHangLapTop.Models;
using WebBanHangLapTop.Repository;

namespace WebBanHangLapTop.Controllers
{
	
	public class ProductController : Controller
	{

		//URL : Product/Add

		private readonly IProductRepository _productRepository;
		private readonly ICategoryRepository _categoryRepository;
        private readonly IBrand _brandRepository;

        public ProductController(IProductRepository productRepository,
		ICategoryRepository categoryRepository,IBrand brandRepository)
		{
			_productRepository = productRepository;
			_categoryRepository = categoryRepository;
            _brandRepository= brandRepository;

        }
		// Hiển thị danh sách sản phẩm

		public IActionResult Layout2()
		{
			return View();	
		}
		public async Task< IActionResult> Index(string searchQuery, int? categoryId, int? brandId)
		{
            IEnumerable<Product> products;

            if (!string.IsNullOrWhiteSpace(searchQuery))
            {
                products = await _productRepository.SearchAsync(searchQuery);
            }
            else
            {
                products = await _productRepository.GetFilteredAsync(categoryId, brandId);
            }
            var categories = await _categoryRepository.GetAllAsync();
            var brands = await _brandRepository.GetAllAsync();

            var viewModel = new HomePageViewModel
            {
                Products = products,
                Categories = categories,
                Brands = brands,
                SearchQuery = searchQuery,
                SelectedCategoryId = categoryId,
                SelectedBrandId = brandId
            };

            return View(viewModel);
        }


    // Hiển thị form thêm sản phẩm mới
    [Authorize(Roles = SD.Role_Admin)]
        public async Task<IActionResult> AddAsync()
		{

			var categories = await _categoryRepository.GetAllAsync();
			ViewBag.Categories = new SelectList(categories, "Id", "Name");
            var brands = await _brandRepository.GetAllAsync();
            ViewBag.Brands = new SelectList(brands, "Id", "BrandName");
            return View();
		}
		// Xử lý thêm sản phẩm mới
		[HttpPost]
		public async Task<IActionResult> Add(Product product,IFormFile ImageUrl, List<IFormFile> Images)
		{
			string url = "";
			if (ModelState.IsValid)
			{
				if (ImageUrl != null)
				{
                   product.ImageUrl = await SaveImage(ImageUrl);
				}


    

				await _productRepository.AddAsync(product, Images);

				return RedirectToAction(nameof(Index));


			}
			// Nếu ModelState không hợp lệ, hiển thị form với dữ liệu đã nhập
			var categories = await _categoryRepository.GetAllAsync();
			ViewBag.Categories = new SelectList(categories, "Id", "Name");
            var brands = await _brandRepository.GetAllAsync();
            ViewBag.brands = new SelectList(brands, "Id", "BrandName");
            return View(product);
		}
		public async Task<IActionResult>Display(int id)
		{
			var product = await _productRepository.GetByIdAsync(id);
		
			if (product == null)
			{
				return NotFound();
			}

			ViewBag.images = await _productRepository.GetAllImagesById(id);

			return View(product);
		}
        // Hiển thị form cập nhật sản phẩm
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Update(int id)
		{
			var product = await _productRepository.GetByIdAsync(id);
			if (product == null)
			{
				return NotFound();
			}
			var categories = await _categoryRepository.GetAllAsync();
			ViewBag.Categories = new SelectList(categories, "Id", "Name",product.CategoryId);
            var brands = await _brandRepository.GetAllAsync();
            ViewBag.Brands = new SelectList(brands, "Id", "BrandName", product);
            return View(product);

		}
		// Xử lý cập nhật sản phẩm
		[HttpPost]
		public async Task<IActionResult> Update(int id, Product product,IFormFile ImageUrl)
		{
			
				if (ImageUrl != null)
				{
						product.ImageUrl=await SaveImage(ImageUrl);	
				}
				if (id != product.Id)
				{
					return NotFound();
				}
				if (ModelState.IsValid)
				{
					await _productRepository.UpdateAsync(product);
					return RedirectToAction(nameof(Index));
				
            }
            return View(product);
		}
        // Hiển thị form xác nhận xóa sản phẩm
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
		{
			var product = await _productRepository.GetByIdAsync(id);
			if (product == null)
			{
				return NotFound();
			}
			return View(product);
		}
		// Xử lý xóa sản phẩm
		[HttpPost]
		public async Task<IActionResult> DeleteProduct(int id)
		{
			await _productRepository.DeleteAsync(id);
			return RedirectToAction(nameof(Index));
		}

     


        private async Task<string> SaveImage(IFormFile image)
		{
			var savePath = Path.Combine("wwwroot/Image", image.FileName);
			using(var fileStream = new FileStream(savePath, FileMode.Create))
			{
				await image.CopyToAsync(fileStream);
			} 
			return "/Image/" + image.FileName;
		}

    }
}

Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebBanHangLapTop.Extension;
using WebBanHangLapTop.Models;
using WebBanHangLapTop.Repository;

namespace WebBanHangLapTop.Controllers
{
    [Authorize]
    public class ShoppingCartController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        public ShoppingCartController(ApplicationDbContext context,
UserManager<ApplicationUser> userManager, IProductRepository
productRepository)
        {
            _productRepository = productRepository;
            _context = context;
            _userManager = userManager;
        }
        public IActionResult Checkout()
        {
            var cart = HttpContext.Session.GetObjectFromJson<ShoppingCart>("Cart");
            var viewModel = new CheckoutViewModel
            {
                Cart = cart,
                // Initialize any other properties if necessary. For example:
                FirstName = "", // These should come from the user input or user's data
                LastName = "",
                PhoneNumber = "",
                ShippingAddress = "",
                Notes = ""
            };

            return View(viewModel);
        }

        
        [HttpPost]
        public async Task<IActionResult> Checkout(Order order)
        {
            var cart =HttpContext.Session.GetObjectFromJson<ShoppingCart>("Cart");
            if (cart == null || !cart.Items.Any())
            {
                // Xử lý giỏ hàng trống...
                return RedirectToAction("Index");
            }
            var user = await _userManager.GetUserAsync(User);
            order.UserId = user.Id;
            order.OrderDate = DateTime.UtcNow;
            order.TotalPrice = cart.Items.Sum(i => i.Price * i.Quantity);
            order.OrderDetails = cart.Items.Select(i => new OrderDetail
            {
                ProductId = i.ProductId,
                Quantity = i.Quantity,
                Price = i.Price
            }).ToList();
            _context.Orders.Add(order);
            await _context.SaveChangesAsync();
            HttpContext.Session.Remove("Cart");
            return View("OrderCompleted", order.Id);
        }
        private async Task<IActionResult> UpdateQuantity(int productId,int quantity)
        {
            var cart = HttpContext.Session.GetObjectFromJson<ShoppingCart>("Cart");

            if (cart != null)
            {
                var cartItem = cart.Items.FirstOrDefault(i => i.ProductId == productId);
                if (cartItem != null)
                {
                    cartItem.Quantity = Math.Max(quantity, 0);

                    if (cartItem.Quantity == 0)
                    {
                        cart.Items.Remove(cartItem);
                    }
                    HttpContext.Session.SetObjectAsJson("Cart", cart);
                }
            }
            return RedirectToAction("Index");

        }
        public async Task<IActionResult> AddToCart(int productId, int quantity)
        {
            // Giả sử bạn có phương thức lấy thông tin sản phẩm từ productId
            var product = await GetProductFromDatabase(productId);
            var cartItem = new CartItem
            {
                ProductId = productId,
                Name = product.Name,
                ImageUrl= product.ImageUrl,
                Price = product.Price,
                Quantity = quantity
            };
            var cart =  HttpContext.Session.GetObjectFromJson<ShoppingCart>("Cart") ?? new
            ShoppingCart();
            cart.AddItem(cartItem);
            HttpContext.Session.SetObjectAsJson("Cart", cart);
            return RedirectToAction("Index");
        }
        public IActionResult Index()
        {
            var cart = HttpContext.Session.GetObjectFromJson<ShoppingCart>("Cart") ?? new ShoppingCart();
            return View(cart);
        }
        private async Task<Product> GetProductFromDatabase(int productId)
        {
            // Truy vấn cơ sở dữ liệu để lấy thông tin sản phẩm
            var product = await _productRepository.GetByIdAsync(productId);
            return product;
        }
        public IActionResult RemoveFromCart(int productId)
        {
            var cart =
            HttpContext.Session.GetObjectFromJson<ShoppingCart>("Cart");
            if (cart is not null)
            {
                cart.RemoveItem(productId);
                // Lưu lại giỏ hàng vào Session sau khi đã xóa mục
                HttpContext.Session.SetObjectAsJson("Cart", cart);
            }
            return RedirectToAction("Index");
        }

    }
}

Views/Shared/Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    @{

    }
    <title>@ViewData["Title"] - WebBanHangLapTop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebBanHangLapTop.styles.css" asp-append-version="true" />

</head>
<body>



    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            @*hiển thị thông tin khác nhau *@
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebBanHangLapTop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="/js/main.js" asp-append-version="true"> </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_InstantSearchResults.cshtml
@model IEnumerable<WebBanHangLapTop.Models.Product>

@if (!Model.Any())
{
    <div>No products found.</div>
}
else
{
    foreach (var product in Model)
    {
        <div class="search-result-item">
            <img src="@product.ImageUrl" alt="@product.Name" />
            <div class="search-result-detail">
                <h6>@product.Name</h6>
                <p>Price: @product.Price</p>
            </div>
        </div>
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tutorial</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebBanHangLapTop.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    @RenderSection("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid justify-content-center">
                <!-- Left-aligned items -->
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="#">WOMAN</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">MAN</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">SALE</a>
                    </li>
                </ul>
                <a class="navbar-brand" style="margin-left:200px" asp-action="index" asp-controller="Home">SPORT LIFE</a>

                <ul class="navbar-nav ms-auto">
                    <!-- Authentication Links -->
                    @Html.Partial("_LoginPartial")
                </ul>
                <form asp-controller="Product" asp-action="Index" method="get" class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search products" aria-label="Search" name="searchQuery">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>

                <a class="btn btn-outline-dark" type="submit" style="margin-left: 10px;" asp-action="Index" asp-controller="ShoppingCart">
                    <i class="bi-cart-fill me-1"></i>
                    Cart
                </a>
                
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Tutorial - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>